### ISSUE TITLE
Crash when placing upgrades on the cart assembler

### ISSUE THREAD

**Issue by Mewtwoy** [modmuss50/SC2#117]
This is making it almost impossible to make carts because you cannot attach any upgrades to it
Works fine if you don't but if trying to do something in creative, it takes a lot of time

Description: Unexpected error

java.lang.ClassCastException: vswe.stevescarts.blocks.tileentities.TileEntityUpgrade cannot be cast to vswe.stevescarts.blocks.tileentities.TileEntityCartAssembler
	at vswe.stevescarts.blocks.BlockCartAssembler.func_180639_a(BlockCartAssembler.java:33)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:96)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by GoryMoon** [comment]
What MC and mod version are you using?
What other mods are you using?

**Comment by Mewtwoy** [comment]
Minecraft version 1.12.2 and mod version is: StevesCarts-1.12.2-2.4.16.81

And as for other mods its: not enough items, xnet, optifine and ironchests (dependencies included)

**Comment by tonimark** [comment]
for me 1.10.2 my game crashes when I shift-right click assembler reproduce: shift and right click on the steve's cart assembler

**Comment by GoryMoon** [comment]
Can't reproduce this in 1.12.2
Can't reproduce the 1.10.2 crash either

**Comment by GoryMoon** [comment]
Check if this have been fixed for you in the latest builds.

**Comment by modmuss50** [comment]
Try breaking and replacing the cart assemeber and upgrades. The incorrect tile is there.
