### ISSUE TITLE
Redstone detectorcusing server crash

### ISSUE THREAD

**Issue by red360** [modmuss50/SC2#148]
After placing Redstone detector and then setting configuration server crashed. MC ver 1.12.2

**Comment by red360** [comment]
Was able to recreate crash in single player.
when appling a red stone signal though a red stone unit into  a detector station.
Station was supplied a signal and then place cart on station.

Crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.7.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 5/30/18 3:06 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=detectortype, clazz=class vswe.stevescarts.helpers.DetectorType, values=[NORMAL, UNIT, STATION, JUNCTION, REDSTONE]} as it does not exist in BlockStateContainer{block=minecraft:redstone_wire, properties=[east, north, power, south, west]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at vswe.stevescarts.helpers.DetectorType.getTypeFromSate(DetectorType.java:103)
	at vswe.stevescarts.blocks.BlockDetector.canConnectRedstone(BlockDetector.java:86)
	at net.minecraft.block.BlockRedstoneWire.canConnectTo(BlockRedstoneWire.java:455)
	at net.minecraft.block.BlockRedstoneWire.func_176339_d(BlockRedstoneWire.java:417)
	at net.minecraft.block.BlockRedstoneWire.func_180656_a(BlockRedstoneWire.java:384)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:388)
	at net.minecraft.world.World.func_175651_c(World.java:3262)
	at net.minecraft.world.World.func_175640_z(World.java:3275)
	at vswe.stevescarts.helpers.OperatorObject$OperatorObjectRedstone.evaluate(OperatorObject.java:152)
	at vswe.stevescarts.helpers.LogicObject.evaluateLogicTree(LogicObject.java:220)
	at vswe.stevescarts.helpers.OperatorObject$1.evaluate(OperatorObject.java:69)
	at vswe.stevescarts.helpers.LogicObject.evaluateLogicTree(LogicObject.java:218)
	at vswe.stevescarts.blocks.tileentities.TileEntityDetector.evaluate(TileEntityDetector.java:250)
	at vswe.stevescarts.helpers.OperatorObject$OperatorObjectRedirector.evaluate(OperatorObject.java:130)
	at vswe.stevescarts.helpers.LogicObject.evaluateLogicTree(LogicObject.java:220)
	at vswe.stevescarts.helpers.OperatorObject$1.evaluate(OperatorObject.java:69)
	at vswe.stevescarts.helpers.LogicObject.evaluateLogicTree(LogicObject.java:218)
	at vswe.stevescarts.blocks.tileentities.TileEntityDetector.evaluate(TileEntityDetector.java:250)
	at vswe.stevescarts.blocks.tileentities.TileEntityDetector.handleCart(TileEntityDetector.java:254)
	at vswe.stevescarts.blocks.BlockRailAdvDetector.onMinecartPass(BlockRailAdvDetector.java:52)
	at net.minecraft.entity.item.EntityMinecart.func_180460_a(EntityMinecart.java:631)
	at vswe.stevescarts.entitys.EntityMinecartModular.func_180460_a(EntityMinecartModular.java:863)
	at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:343)
	at vswe.stevescarts.entitys.EntityMinecartModular.func_70071_h_(EntityMinecartModular.java:989)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at vswe.stevescarts.helpers.DetectorType.getTypeFromSate(DetectorType.java:103)
	at vswe.stevescarts.blocks.BlockDetector.canConnectRedstone(BlockDetector.java:86)
	at net.minecraft.block.BlockRedstoneWire.canConnectTo(BlockRedstoneWire.java:455)
	at net.minecraft.block.BlockRedstoneWire.func_176339_d(BlockRedstoneWire.java:417)
	at net.minecraft.block.BlockRedstoneWire.func_180656_a(BlockRedstoneWire.java:384)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185911_a(BlockStateContainer.java:388)
	at net.minecraft.world.World.func_175651_c(World.java:3262)
	at net.minecraft.world.World.func_175640_z(World.java:3275)
	at vswe.stevescarts.helpers.OperatorObject$OperatorObjectRedstone.evaluate(OperatorObject.java:152)
	at vswe.stevescarts.helpers.LogicObject.evaluateLogicTree(LogicObject.java:220)
	at vswe.stevescarts.helpers.OperatorObject$1.evaluate(OperatorObject.java:69)
	at vswe.stevescarts.helpers.LogicObject.evaluateLogicTree(LogicObject.java:218)
	at vswe.stevescarts.blocks.tileentities.TileEntityDetector.evaluate(TileEntityDetector.java:250)
	at vswe.stevescarts.helpers.OperatorObject$OperatorObjectRedirector.evaluate(OperatorObject.java:130)
	at vswe.stevescarts.helpers.LogicObject.evaluateLogicTree(LogicObject.java:220)
	at vswe.stevescarts.helpers.OperatorObject$1.evaluate(OperatorObject.java:69)
	at vswe.stevescarts.helpers.LogicObject.evaluateLogicTree(LogicObject.java:218)
	at vswe.stevescarts.blocks.tileentities.TileEntityDetector.evaluate(TileEntityDetector.java:250)
	at vswe.stevescarts.blocks.tileentities.TileEntityDetector.handleCart(TileEntityDetector.java:254)
	at vswe.stevescarts.blocks.BlockRailAdvDetector.onMinecartPass(BlockRailAdvDetector.java:52)
	at net.minecraft.entity.item.EntityMinecart.func_180460_a(EntityMinecart.java:631)
	at vswe.stevescarts.entitys.EntityMinecartModular.func_180460_a(EntityMinecartModular.java:863)
	at net.minecraft.entity.item.EntityMinecart.func_70071_h_(EntityMinecart.java:343)
	at vswe.stevescarts.entitys.EntityMinecartModular.func_70071_h_(EntityMinecartModular.java:989)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: stevescarts:cart.0 (vswe.stevescarts.entitys.EntityMinecartModular)
	Entity ID: 63672
	Entity Name: entity.Minecart.Vswe.0.name
	Entity's Exact location: -1045.50, 80.06, 230.50
	Entity's Block location: World: (-1046,80,230), Chunk: (at 10,5,6 in -66,14; contains blocks -1056,0,224 to -1041,255,239), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: ULXMT
	All players: 1 total; [EntityPlayerMP['XRED_360'/1063, l='ULXMT', x=-1045.33, y=80.00, z=232.55]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 864314869
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by modmuss50** [comment]
Let me know if it still happens on the new version.

**Comment by red360** [comment]
Works now. Thanks for the fast turn around.
Also the detector Junction does not switch the advanced detector rail directions, but the detector unit works in its place.

**Comment by GoryMoon** [comment]
@red360 Just tested the detector junction and it works as intended, cart going over top it and is valid for the setup in it and it changes the track. https://gfycat.com/ImprobableTidyLark
