### ISSUE TITLE
Issue with IC2 classic on load

### ISSUE THREAD

**Issue by CLOUDSofSTEEL** [modmuss50/SC2#81]
I'm not sure if this is more from IC2C or SC, but when loading the two together this error occurs:

Caused by: java.lang.NoClassDefFoundError: ic2/core/item/type/MiscResourceType
	at vswe.stevescarts.compat.ic2.CompatIC2.loadAddons(CompatIC2.java:15)
	at vswe.stevescarts.plugins.PluginLoader.init(PluginLoader.java:62)
	at vswe.stevescarts.StevesCarts.load(StevesCarts.java:97)

I've went through both mods' configs to find something relevant, but I'm not seeing anything.

**Comment by modmuss50** [comment]
IC2 classic isn't supported, please use the official ic2 found at: http://jenkins.ic2.player.to/

**Comment by CLOUDSofSTEEL** [comment]
I really wanted to play with IC2C. Official IC2 has lost it's charm. I'll just have to get rid of one of the mods I guess. Thanks for the quick reply.
